### PR TITLE
Removed problematic local executor specification

### PR DESCRIPTION
**Pull request by alneberg**
Related to https://github.com/nextflow-io/nextflow/issues/693#issuecomment-391792952 and https://github.com/nf-core/cookiecutter/issues/30

### CODE REVIEW

**Comment by alneberg** [comment]
@ewels, I think this PR is faulty? Feel free to close this one if you agree.

**Comment by ewels** [comment]
Faulty how? Looks good to me!

**Comment by ewels** [comment]
The tests are failing because the travis config hasn’t been set up yet (its blank).

**Comment by alneberg** [comment]
Ok, if you think it looks good, then I'm pleased! I just thought it was one of those other cases where there were no "script" defined so that it would actually make sense to force it to run locally?

**Comment by pditommaso** [comment]
In this case it's fine to have `executor 'local'` because the process execute groovy code, not an bash script. Removing the `local`executor it will print a warning message when running the workflow in a cluster/cloud.

**Comment by ewels** [comment]
Yes, I didn't read far enough down the diff to realise that it was an `exec` not a `script`. The process name has been updated in other repos to use a script and run as a regular process, so I think it's fine to remove it like this, as we'll almost certainly update it further in the future.

Thanks for the clarification though @pditommaso! 👍

**Pull request merged**
